### PR TITLE
Add user session

### PR DESCRIPTION
**Pull request by manandearth**
## Goal
User session, authentication. (log in/ log out) 
## Proposed changes
- Adding user column to the db 
- hashing the password
- logout
## PR status, roadblocks, etc
  register and login done. 
need to test persistence of session

### CODE REVIEW

**Comment by manandearth** [comment]
I want a view (specifically the `header-links` that renders with every route) to access the `:identity` in order to have a :  "logged as: foo" in that html element. as well as a predicate for `(if-let [identity (:identity session])`  so I could switch between:

```
[ Home | About | Add an entry | All Entries | Login ]
```
and
``` 
[ Home | About | Add an entry | All Entries | Logged as FOO | logout ]
```

But I want to keep the views free from the data.

**Comment by manandearth** [comment]
Sorry for wrong tense on the commit message... I am a bit under the weather today.

`/logout` doesn't work. ( I am checking this only by running it in the browser, and `/greet` has a predicate that takes the `:session :identity` , But I believe there should be  a better way to check in the repl what is the state of `:session` , what would that be?

**Comment by manandearth** [comment]
The problem was the route, same conflict as we had between `/foo/:id` and `/foo/bar` routes, resolved using a new route `/foo-bar` ... only in this case here the conflict is between `/login` and `/logout` .
@vemv you sent a link to that issue with Pedestal... I found [this](https://github.com/pedestal/pedestal/pull/330)

The next thing to look at is the interceptors, I have three added : `flash` 'session` and `authentication` , In the example in the [pedestal samples](https://github.com/pedestal/pedestal/blob/master/samples/buddy-auth/src/buddy_auth/service.clj) it is more concise, But I have somewhat a bit lost with interceptors.. It works but I need a step back, then I'll rearrange the code.

And another thing is the division of responsibilities, The views are less tidy with some destructuring on [login](https://github.com/manandearth/playground/blob/564f235a095c42e9a1fe511268d068d1f29b6877/src/playground/views.clj#L54), 

and the handlers [for example logout-handler](https://github.com/manandearth/playground/blob/564f235a095c42e9a1fe511268d068d1f29b6877/src/playground/service.clj#L56) has some logic that is perhaps out of place. I will find a better way.

**Comment by manandearth** [comment]
Actually, the `\log-out` route is not working consistently.

So I think that unless I made some mistake in my interceptors, `buddy-auth` should be a component and not a pedestal interceptor..  
The lambdaisland [example](https://github.com/lambdaisland/booklog/blob/ep28-end/src/clj/booklog/application.clj) is a clean implementation using the built-in `wrap-authentication` but that's for `compojure`. How will this be done in `pedestal`?

**Comment by manandearth** [comment]
I think at this stage it's time to revert, I was juggling too many unknowns. very unscientific. sorry.
My number one problem is not knowing how to test the routes in little bites. That leaves me not completely understanding the working of the interceptors. 
I am happy to start this branch from scratch.

**Comment by vemv** [comment]
Alright, yes, thank you for keeping it clean!

**Comment by manandearth** [comment]
I'm trying to...
starting a `repl-test-tools` branch now.

**Comment by manandearth** [comment]
Also for the next step, I saw two examples that are relevant for implementing buddy,

One was a `session backend` using a wrapper for `compojure` in a `component` system:
 https://github.com/lambdaisland/booklog/blob/ep28-end/src/clj/booklog/application.clj

The other is `basic backend` in `pedestal` (no `component`):
https://github.com/pedestal/pedestal/blob/master/samples/buddy-auth/src/buddy_auth/service.clj 

My attempt in the [authenticate branch](https://github.com/manandearth/playground/pull/9/commits/1ef05ea3bd03bcc08e140d74b6e86925fb15f577) was borrowing mostly from the `pedestal` example, I think that in playground we need a mix of the two: a `buddy` component that wraps on `pedestal`.

**Pull request closed without merging**
